CREATE DATABASE TCS
USE TCS
GO
CREATE TABLE ODC
(
ODC_ID INT PRIMARY KEY,
ODC_NAME VARCHAR(50)NOT NULL
)
CREATE TABLE IT_EMPLOYEES
(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR (50) NOT NULL,
GENDER CHAR(6),
SALARY MONEY,
DOJ DATE,
ODC_ID INT
FOREIGN KEY (ODC_ID) REFERENCES ODC(ODC_ID)
)
INSERT INTO ODC VALUES
(1001,'ABC'),
(1002,'XYZ'),
(1003,'PQR'),
(1004,'KLM');

INSERT INTO IT_EMPLOYEES VALUES
(1,'SOWMYA','F',30000,'2025-04-20',1001),
(2,'SRINIVAS','M',40000,'2021-04-20',1002),
(3,'HIMAJA','F',10000,'2025-08-20',1003),
(4,'DIVYA','F',20000,'2020-04-20',1004);
SELECT* FROM ODC
SELECT * FROM IT_EMPLOYEES

SELECT D.ODC_NAME,
       E.EMP_NAME,
	   E.SALARY
FROM IT_EMPLOYEES AS E
INNER JOIN ODC AS D
ON D.ODC_ID=E.ODC_ID

SELECT D.ODC_NAME,
       E.EMP_NAME,
	   E.SALARY
FROM IT_EMPLOYEES AS E
LEFT JOIN ODC AS D
ON D.ODC_ID=E.ODC_ID


SELECT D.ODC_NAME,
       E.EMP_NAME,
	   E.SALARY
FROM IT_EMPLOYEES AS E
RIGHT JOIN ODC AS D
ON D.ODC_ID=E.ODC_ID


SELECT D.ODC_NAME,
       E.EMP_NAME,
	   E.SALARY
FROM IT_EMPLOYEES AS E
FULL JOIN ODC AS D
ON D.ODC_ID=E.ODC_ID


SELECT D.ODC_NAME,
       E.EMP_NAME,
	   E.SALARY
FROM IT_EMPLOYEES AS E
CROSS JOIN ODC AS D

SELECT 
COUNT(*) AS TOTAL_IT_EMP,
SUM(SALARY) AS TOTAL_SALARY,
AVG(SALARY) AS AVG_SALARY,
MIN(SALARY) AS MIN_SALARY,
MAX(SALARY) AS MAX_SALARY
FROM IT_EMPLOYEES

SELECT
D.ODC_NAME,
COUNT(*)  AS TOTAL_STAFF,
SUM(E.SALARY) AS TOTALAMOUNT,
MAX(E.SALARY) AS MAXAMOUNT,
AVG(E.SALARY) AS AVGTOTAL
FROM IT_EMPLOYEES AS E
INNER JOIN ODC AS D
ON E.ODC_ID=D.ODC_ID
GROUP BY D.ODC_NAME
HAVING COUNT(*)>1
ORDER BY AVGTOTAL DESC;

SELECT*FROM IT_EMPLOYEES
WHERE SALARY>20000;





